version: '3'
services:
  strapi:
    image: strapi/strapi
    container_name: devin-strapi
    environment:
      URL_API: 'http://localhost:1337'
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - './app:/srv/app'
    ports:
      - '1337:1337'
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: devin-mongo
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - './data:/data/db'
